config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'pages#home'

  get 'users/:id/dashboard', to: 'users#dashboard', as: :dashboard
  resources :users, only: [] do
    resources :surfboards, only: [:new, :create]
  end

  resources :surfboards, only: [:index, :show, :edit, :update, :create] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :update, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :surfboard
  has_many :reviews

  validates :collection_date, :return_date, :price_per_day, presence: true
  before_validation :add_price_per_day

  def add_price_per_day
    self.price_per_day = surfboard.price_per_day
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  has_one :surfboard, through: :booking

  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/models/surfboard.rb
class Surfboard < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :length, :volume, :price_per_day, presence: true, numericality: { only_integer: true }
  validates :name, :board_type, :fin_type, :brand, :description, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Bookings and reviews should maybe not be dependent destroy in final
  has_many :bookings, dependent: :destroy
  has_many :surfboards, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :photo])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :update]

  def new
    @booking = Booking.new
    @surfboard = Surfboard.find(params[:surfboard_id])
    @booking.surfboard = @surfboard
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @surfboard = Surfboard.find(params[:surfboard_id])
    @booking.surfboard = @surfboard
    @booking.user = User.find(current_user.id)
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @review = Review.new(booking: @booking)
    authorize @booking
  end

  def update
    @booking.accepted = accepted_to_boolean
    @booking.save
    authorize @booking
    redirect_to dashboard_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:collection_date, :return_date)
  end

  def accepted_to_boolean
    params[:booking][:accepted] == "true"
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @surfboards = Surfboard.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_booking, only: [:new, :create]

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/controllers/surfboards_controller.rb
class SurfboardsController < ApplicationController
  def index
    @surfboards = policy_scope(Surfboard).order(created_at: :desc)
    @surfboards = @surfboards.reject { |surfboard| surfboard.user == current_user }
  end

  def show
    @surfboard = Surfboard.find(params[:id])
    @booking = Booking.new(surfboard: @surfboard)
    authorize @surfboard
  end

  def new
    @surfboard = Surfboard.new
    @user = User.find(params[:user_id])
    authorize @surfboard
  end

  def create
    @surfboard = Surfboard.new(surfboard_params)
    @surfboard.user = User.find(params[:user_id])
    authorize @surfboard
    if @surfboard.save
      redirect_to surfboard_path(@surfboard), notice: 'Surfboard was successfully created.'
    else
      render :new
    end
  end

  def edit
    @surfboard = Surfboard.find(params[:id])
    authorize @surfboard
  end

  def update
    @surfboard = Surfboard.find(params[:id])
    @surfboard.update(surfboard_params)
    authorize @surfboard
    redirect_to surfboard_path(@surfboard)
  end

  private

  def surfboard_params
    params.require(:surfboard).permit(:name, :length, :volume, :price_per_day, :board_type, :fin_type, :brand, :description, :photo, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = User.find(current_user.id)

    # Surfboard bookings - where user is the owner of the surfboard. BETTER
    @surfboard_upcoming_bookings = Booking.joins(:surfboard).where(surfboards: { user_id: @user.id }).where(bookings: { accepted: true }).where("collection_date >= ?", Date.today)
    @surfboard_current_bookings = Booking.joins(:surfboard).where(surfboards: { user_id: @user.id }).where(bookings: { accepted: true }).where("collection_date < ?", Date.today).where("return_date >= ?", Date.today)
    @surfboard_pending_bookings = Booking.joins(:surfboard).where(surfboards: { user_id: @user.id }).where(bookings: { accepted: nil }).where("collection_date >= ?", Date.today)
    @surfboard_past_bookings = Booking.joins(:surfboard).where(surfboards: { user_id: @user.id }).where(bookings: { accepted: true }).where("return_date < ?", Date.today)
    @surfboard_bookings_size = (@surfboard_upcoming_bookings.size + @surfboard_current_bookings.size + @surfboard_pending_bookings.size + @surfboard_past_bookings.size)

    # User bookings - where user is the renter of the surfboard
    @user_bookings = User.find(current_user.id).bookings
    @user_upcoming_bookings = User.find(current_user.id).bookings.where(accepted: true).where("collection_date >= ?", Date.today)
    @user_current_bookings = User.find(current_user.id).bookings.where(accepted: true).where("collection_date < ?", Date.today).where("return_date >= ?", Date.today)
    @user_pending_bookings = User.find(current_user.id).bookings.where(accepted: nil).where("collection_date >= ?", Date.today)
    @user_past_bookings = User.find(current_user.id).bookings.where(accepted: true).where("return_date < ?", Date.today)
    @user_bookings_size = (@user_upcoming_bookings.size + @user_current_bookings.size + @user_pending_bookings.size + @user_past_bookings.size)

    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-between my-5">
    <h1 class="text-center">Book <%= @surfboard.name %></h1>
    <div>
      <%= link_to "Back to surfboard", surfboard_path(@surfboard), class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto">

      <div class="form-container my-3">
        <%= simple_form_for [@surfboard, @booking] do |f| %>
          <%= f.input :collection_date, html5: true %>
          <%= f.input :return_date, html5: true %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container my-5">
  <div class="row justify-content-between">
    <h1>Booking for <%= @booking.surfboard.name %></h1>
    <div>
      <%= link_to "Back to surfboard", surfboard_path(@booking.surfboard), class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>


<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card-surfboard-show">
        <% if @booking.surfboard.photo.attached? %>
        <div class="card-box">
          <%= cl_image_tag @booking.surfboard.photo.key, width: 400, height: 400, crop: :thumb, gravity: :face, class: "surfboard-index-img"%>
        </div>
        <% end %>
        <div class="card-surfboard-show-info">
          <p><strong>Collection date: </strong><%= @booking.collection_date %></p>
          <p><strong>Return date: </strong><%= @booking.return_date %></p>
          <p><strong>Price per day: </strong>$<%= @booking.price_per_day %></p>
          <p><strong>Status: </strong><%= @booking.accepted %></p>
          <p><strong>Owner: </strong><%= @booking.surfboard.user.name %></p>
          <% if @booking.surfboard.user.photo.attached? %>
          <%= cl_image_tag @booking.surfboard.user.photo.key, class: "avatar-bordered" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-center my-2">
          <% if policy(@review).new? %>
          <%= link_to "Leave a review", new_booking_review_path(@booking), class: "btn btn-sm btn-outline-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/update.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1 class="text-center my-5">Update booking details%></h1>

      <div class="form-container my-3">
        <%= simple_form_for [@surfboard, @booking] do |f| %>
          <%= f.input :collection_date, html5: true %>
          <%= f.input :return_date, html5: true %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "single-fin-simple.jpeg", class:"avatar" %>
  <% end %>
  <div class="d-flex justify-content-center align-items-center p-2">
    <h1>surf-sticks</h1>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item-active">
        <%= link_to "Surfboards", "/surfboards", class: "nav-link" %>
      </li>
      <li class="nav-item-active">
        <%= link_to "Dashboard", "/users/51/dashboard", class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Surf Sticks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%#= render '/layouts/navbar' %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
 <div class="home">
  <div class="bg-light d-flex justify-content-center align-items-center p-5">
  </div>
  <div class="main-body">
    <div class="banner d-flex justify-content-between align-items-center backgroud-green">
      <div class="p-3">
        <h2>rent sick surf sticks at surfsticks.com</h2>
        <br>
        <h3 class="mt-4">try out epic surfboards for cheap</h3>
        <h3 class="mt-4">rent your old surfboards to other groms</h3>
        <h3 class="mt-4">no more bringing surfboards on your surftrips</h3>
      </div>
      <%= image_tag "drink-surf-two.jpg", width: 400, height: 400, marging: 10 %>
    </div>
  </div>
  <div class="bg-light d-flex justify-content-center align-items-center p-5">
    <h2>Featured Surfboards in Canggu</h2>
  </div>
<div class="row">
    <% @surfboards.limit(5).each do |surfboard| %>
    <div class="col-xs-12 col-md-8 col-xl-6 mb-3 mx-auto">
      <%= link_to surfboard_path(surfboard) do %>

      <div class="card-surfboard">
        <div>
          <% if surfboard.photo.attached? %>
          <%= cl_image_tag surfboard.photo.key, width: 200, height: 200, crop: :thumb, gravity: :face, class: "surfboard-index-img"%>
        <% end %>
        </div>
        <div class="card-surfboard-infos">
          <div class="surfboard-title">
            <% feet = surfboard.length / 12 %>
            <% inches = surfboard.length % 12 %>
            <% length = "#{feet}'#{inches}\"" %>
            <h2><%= length %> <%= surfboard.name %></h2>
            <p><%= surfboard.description %></p>
          </div>
          <div class="surfboard-additional-info">
            <div class="surfboard-rating">
              <% num_ratings = surfboard.reviews.size %>
              <% total_score = surfboard.reviews.map { |review| review.rating }.sum %>
              <% avg_rating = total_score.positive? ? total_score.fdiv(num_ratings) : "N/A" %>
              <p><i class="fas fa-star"></i> <%= avg_rating%> (<%= num_ratings %> reviews)</p>
            </div>
            <div class="surfboard-pricing">
              <p>$ <%= surfboard.price_per_day %> / day</p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">

      <h1 class="text-center my-5">Leave a review for <%= @booking.surfboard.user.name %></h1>

      <%= simple_form_for [@booking, @review] do |f| %>
        <%=f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
        <%=f.input :comment %>
        <%=f.submit class: 'btn btn-sm btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="surf-sticks-navbar" class="justify-content-between navbar navbar-light navbar-lewagon navbar-expand-sm ">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "single-fin-simple.jpeg", class:"avatar" %>
  <% end %>
  <%= link_to "/", class: "navbar-brand" do %>
    <div class="d-flex justify-content-center">
      <h1>surfsticks</h1>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item-active">
        <%= link_to "Surfboards", "/surfboards", class: "nav-link", style: 'color:white; letter-spacing: 2px; margin-right: 5px' %>
      </li>
      <li class="nav-item-active">
        <%= link_to "Dashboard", "/users/#{current_user.id}/dashboard", class: "nav-link", style: 'color:white; letter-spacing: 2px; margin-right: 15px' %>
      </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else  %>
            <%= image_tag "user-black.svg", width: 40, height: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item"><strong><%= current_user.username.capitalize %></strong></p>
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", style: 'color:white; letter-spacing: 2px; margin-right: 5px' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/surfboards/edit.html.erb
<div class="container">
  <div class="row justify-content-between my-5">
    <h1>Edit <%= @surfboard.name %></h1>
    <div>
      <%= link_to "Back to surfboard", surfboard_path(@surfboard), class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <div class="row">


    <div class="col-md-8 mx-auto">


      <%= simple_form_for [@surfboard] do |f| %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :board_type %>
          <%= f.input :fin_type %>
          <%= f.input :brand %>
          <%= f.input :length %>
          <%= f.input :volume %>
          <%= f.input :price_per_day %>
          <%= f.input :address %>
          <%= f.input :photo, as: :file %>
        </div>

      <div class="form-actions">
        <%= f.submit %>
      </div>
      <% end %>

      <%= link_to 'Back', surfboards_path %>
    </div>
  </div>
</div>

app/views/surfboards/index.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col">
      <h2>All surfboards</h2>
    </div>
  </div>

  <div class="row">
    <% @surfboards.each do |surfboard| %>
    <div class="col-xs-12 col-md-8 col-xl-6 mb-3 mx-auto">
      <%= link_to surfboard_path(surfboard) do %>

      <div class="card-surfboard">
        <div>
          <% if surfboard.photo.attached? %>
          <%= cl_image_tag surfboard.photo.key, width: 200, height: 200, crop: :thumb, gravity: :face, class: "surfboard-index-img"%>
        <% end %>
        </div>
        <div class="card-surfboard-infos">
          <div class="surfboard-title">
            <% feet = surfboard.length / 12 %>
            <% inches = surfboard.length % 12 %>
            <% length = "#{feet}'#{inches}\"" %>
            <h2><%= length %> <%= surfboard.name %></h2>
            <p><%= surfboard.description %></p>
          </div>
          <div class="surfboard-additional-info">
            <div class="surfboard-rating">
              <% num_ratings = surfboard.reviews.size %>
              <% total_score = surfboard.reviews.map { |review| review.rating }.sum %>
              <% avg_rating = total_score.positive? ? total_score.fdiv(num_ratings) : "N/A" %>
              <p><i class="fas fa-star"></i> <%= avg_rating%> (<%= pluralize num_ratings, "review" %>)</p>
            </div>
            <div class="surfboard-pricing">
              <p>$ <%= surfboard.price_per_day %> / day</p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
    <% end %>
  </div>
</div>

app/views/surfboards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">

      <h1>Add a new surfboard</h1>

      <%= simple_form_for [@user, @surfboard] do |f| %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :board_type %>
          <%= f.input :fin_type %>
          <%= f.input :brand %>
          <%= f.input :length %>
          <%= f.input :volume %>
          <%= f.input :price_per_day %>
          <%= f.input :address %>
          <%= f.input :photo, as: :file %>
        </div>

      <div class="form-actions">
        <%= f.submit %>
      </div>
      <% end %>

      <%= link_to 'Back', surfboards_path %>
    </div>
  </div>
</div>

app/views/surfboards/show.html.erb
<div class="container my-5">
  <div class="row justify-content-between">
    <h1><%= @surfboard.name %></h1>
    <% if policy(@booking).new? %>
      <div>
        <%= link_to "Make a booking", new_surfboard_booking_path(@surfboard), class: "btn btn-outline-secondary" %>
      </div>
    <% end %>
    <% if policy(@surfboard).edit? %>
      <div>
        <%= link_to "Edit surfboard", edit_surfboard_path(@surfboard), class: "btn btn-outline-secondary" %>
      </div>
    <% end %>

  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card-surfboard-show">
        <% if @surfboard.photo.attached? %>
        <div class="card-box">
        <%= cl_image_tag @surfboard.photo.key, width: 400, height: 400, crop: :thumb, gravity: :face, class: "surfboard-index-img"%>
        </div>
        <% end %>
          <div class="card-surfboard-show-info">
            <% feet = @surfboard.length / 12 %>
            <% inches = @surfboard.length % 12 %>
            <% length = "#{feet}'#{inches}\"" %>
            <h2><%= length %> <%= @surfboard.name %></h2>
            <p><strong>Description: </strong><%= @surfboard.description %></p>
            <p><strong>Volume: </strong><%= @surfboard.volume %> liters</p>
            <p><strong>Board type: </strong><%= @surfboard.board_type %></p>
            <p><strong>Fin type: </strong><%= @surfboard.fin_type %></p>
            <p><strong>Brand: </strong><%= @surfboard.brand %></p>
            <p><strong>Owner: </strong><%= @surfboard.user.username %></p>
            <h2 class="card-trip-pricing">Price per day: $<%= @surfboard.price_per_day %></h2>
          </div>
      </div>
    </div>
  </div>

  <div class="row my-5">
    <div class="col">
        <h2>Reviews for <%= @surfboard.name %></h2>
        <% @surfboard.reviews.each do |review| %>
        <div class="card-review">
          <p><em>"<%= review.comment %>!"</em> shouts <%= review.user.username %></p>
          <p>Rating: <%= review.rating %> / 5</p>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">
  <div class="row my-5 justify-content-between">
    <h1><%= current_user.name %></h1>
    <div>
      <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, width: 56, height: 56, crop: :thumb, gravity: :face, class: "avatar-large" %>
      <% end %>
    </div>
  </div>

  <% unless current_user.surfboards.size.zero? %>
    <!-- We won't display this if they have no surfboards -->
  <div class="row my-5">
    <h2 class="text-center">Bookings for your surfboards</h2>
  </div>
  <% end %>

  <!-- Let's add in an if statement here so that if there is no data we write an empty statement - otherwise we render 4 cards-->

  <% if @surfboard_bookings_size.zero? %>
    <!-- Placeholder for those with surfboards but no bookings -->
    <h3 class="text-center">There are no bookings for your surfboards (yet!)</h3>
  <% else %>
    <div class="row">
      <% unless @surfboard_current_bookings.empty? %>
        <div class="col-xs-12 col-lg-8 col-xl-6 mb-3 mx-auto">
          <%= render 'surfboard_bookings', bookings: @surfboard_current_bookings, bookings_name: "Current Bookings" %>
        </div>
      <% end %>
      <% unless @surfboard_upcoming_bookings.empty? %>
        <div class="col-xs-12 col-lg-8 col-xl-6 mb-3 mx-auto">
          <%= render 'surfboard_bookings', bookings: @surfboard_upcoming_bookings, bookings_name: "Upcoming Bookings" %>
        </div>
      <% end %>

      <% unless @surfboard_pending_bookings.empty? %>
        <div class="col-xs-12 col-lg-8 col-xl-6 mb-3 mx-auto">
          <%= render 'surfboard_bookings', bookings: @surfboard_pending_bookings, bookings_name: "Pending Bookings" %>
        </div>
      <% end %>

      <% unless @surfboard_past_bookings.empty? %>
        <div class="col-xs-12 col-lg-8 col-xl-6 mb-3 mx-auto">
          <%= render 'surfboard_bookings', bookings: @surfboard_past_bookings, bookings_name: "Past Bookings"  %>
        </div>
      <% end %>
    </div>
  <% end %>


  <% unless current_user.bookings.size.zero? %>
    <!-- We won't display this if they have no bookings -->
    <div class="row my-5">
      <h2 class="text-center">Your bookings for others' surfboards</h2>
    </div>

    <div class="row my-5">
      <%= render 'user_bookings', bookings: @user_bookings %>
    </div>
  <% end %>




  <div class="row my-5 justify-content-between">
    <h2>Your surfboards</h2>
    <div>
      <%= link_to "Add a surfboard", new_user_surfboard_path(current_user), class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <div class="row my-5">
    <%= render 'surfboards', surfboards: current_user.surfboards %>
  </div>

</div>